### ISSUE TITLE
Clarify Extensions requirement: "The project does not conflict with other official projects"

### ISSUE THREAD

**Issue by twomice** [civicrm/civicrm-dev-docs#107]
Hi @totten ,

From https://docs.civicrm.org/dev/en/master/extend-stages/#review-criteria: "The project does not conflict with other official projects"

In a recent conversation in the Extensions WG, we were unclear on the specific meaning of the word "conflict" here, and we'd like to be able to explain this requirement to new reviewers -- and ourselves :-). Could I ask you for an example or two?

**Comment by totten** [comment]
Good question. It can be interpreted a couple ways, e.g.
 * If you apply a more technical interpretation, then you might say that *all official extensions can be installed at the same time.*. For example, if two extensions both create a table called `civicrm_foo`, then you can't install one without breaking the other. If two extensions both put a redirect at the end of the same form, then only one redirect can actually take effect. These are technical conflicts where one prevents the other from working.
 * If you apply a more marketing/business-level interpretation, then you might say that *all official extensions need to serve a unique purpose.* If two official extensions implement Authorize.net payment processing, then admins will perceive the design as conflicted (because there's no clear guidance on how to handle an Authorize.net payment).

Note that this review item is listed as "Suggested" but not "Required". There's a couple reasons for this:
 * From the perspective of an extension author, the existence of some conflict seems like an externality which they don't fully control. An extension may fluctuate between conflicted+unconflicted over time (even if its own code stays the same). An extension shouldn't be completely banned to due to transient or external factors.
 * However, we do need to present our users/admins with cogent experience, and we need to put some pressure on extension authors to keep the parts aligned, avoid conflicts+duplication, etc.

Treating this as a soft rule gives reviewers a chance to make a judgment-call (and signals to authors that they should avoid conflicts if they want an easy review). Of course, if someone has a better way to balance these concerns, they can open a PR and discuss it. ;)

**Comment by twomice** [comment]
Thanks, Tim! @seanmadsen, @nganivet, and @GinkgoFJG let's consider whether this needs any discussion on our next Ext-WG call.
