### ISSUE TITLE
Orange light code

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-dev-docs#11]
I just wanted to start a scribble pad for some of the code-patterns currently in the codebase that I think should be discouraged or things I try to discourage in PRs

1) Joins on the option_value table rather than using pseudoconstants - this is highly like to cause an unindexed query so we actively discourage it

2) passing variables by reference - the tide turned on this pattern around 2010 when Xavier pointed out it doesn't save memore due to php lazy loading. The disadvantage of passing & altering a variable compared to returning a variable is that it encourages people to alter the variables to achieve poorly documented, unintuitive or highly fragile outcomes.

3) increasing code complexity without increasing test coverage - increases code fragility

4) silly checks in functions ie  checking if one of the parameters in the signature is empty & returning if so - there may be a case for this but often we are just enabling the calling function to do the wrong thing

5) compiled sql. In order of preference for secure concise predictable code we recommend:
- api 
- DAO
- CRM_Utils_Select
- compiled sql

6) $session = CRM_Core_Session; $userId = $session->get('UserID');
Use CRM_Core_Session->getLoggedInUser()

more to come as I hit them

RE BAOs and apis - it is fine to call a BAO from the api - as long as you do not call the 'same' api - ie. Contribution.Delete api should not be called from BAO_Contribution::delete() as that would be circular. Ditto create.

Create apis call create & add on the BAO, Delete apis call delete() and del() on the BAO (or DAO). Get apis only access the BAO in some of our would-like-to-deprecate apis. The general goal here is to ditch the api v3 get apis that do that

**Comment by michaelmcandrew** [comment]
@eileenmcnaughton - is the idea to turn this issue into a page in the new documenation at some point? If so, one approach would be to create a branch of the dev docs and add it there.

**Comment by ErichBSchulz** [comment]
I'm happy to take on the task of adding this in to the dev docs @eileenmcnaughton @michaelmcandrew 

these are exactly the kinds of style tips I've been looking for

**Comment by ErichBSchulz** [comment]
happy to do this @seanmadsen - seem to tie into https://wiki.civicrm.org/confluence/display/CRMDOC/Coding+Standards which has your name against it but no path yet

want me to take on coding standards?

**Comment by xurizaemon** [comment]
> it is fine to call a BAO from the api

Thanks @eileenmcnaughton - my question over on  eileenmcnaughton/civicrm-core@f139ac07 which prompted this comment was: if it's OK to call a BAO from API, and OK to call API from BAO, how do we know when to do which? (In `CRM_Contribute_BAO_ContributionSoft::processSoftContribution()` there's a call to `civicrm_api3('ContributionSoft', 'delete')`, which has me wondering whether I can treat API and BAO as defined "layers" or whether that distinction is not true.

**Comment by eileenmcnaughton** [comment]
Really the BAO has some defined functions - basically a create function, if required and a delete function, if required. The rest is just a random collection of functions.

Generally we encourage as much api use as possible because it's more tested & more predictable, however the create function will always be required on many BAOs

**Comment by totten** [comment]
> If it's OK to call a BAO from API, and OK to call API from BAO, should we be able to know when it's OK to do which?

The overall subsystem dependencies should be the first factor in determining whether to call any API/BAO/SQL/whatever. For general examples: CiviMember depends on CiviContribute, but CiviMail and CiviContribute should not depend on each other. (Once you've decided that a dependency makes sense, it's preferable to use an interface that's tested -- and `civicrm_api3()` stuff tends to be better tested. But you *can* write tests for anything.)

For messy concrete examples, try running `grep -r CRM_Mailing CRM/Profile/ CRM/Event/ CRM/Contribute/ CRM/Member/ CRM/Contact`. Those are all code-smells. However, it's not as simple as saying that all those should be changed to use `civicrm_api3()`. Addressing each code-smell really requires something different, e.g. a couple examples:
 * `CRM/Profile/Form/Edit.php` isn't really using CiviMail for mailblasts-- it was just a way to evaluate tokens. This smell indicated that our token handling was underdeveloped. (Now-a-days, it should probably call `TokenProcessor`.)
 * *Maybe* the `commonSubscribe()` stuff should be an API. *Maybe*. I don't have a glib answer for this one.
 * `CRM/Contact/Task.php` lists several tasks that aren't really provided by `CRM/Contact` and depends on several external symbols. At time of writing, there hasn't been a good way to put the declarations closer to their home (because internal architecture for events/declarations has been underdeveloped).

**Comment by seamuslee001** [comment]
@seanmadsen i think this can close now that https://docs.civicrm.org/dev/en/latest/standards/#orange-light-code is there and that should be where not great patterns are added

**Comment by eileenmcnaughton** [comment]
Sold
