### ISSUE TITLE
Auto-generate a summary page with name and short description of all hooks

### ISSUE THREAD

**Issue by seanmadsen** [civicrm/civicrm-dev-docs#132]
It'd be nice to be able to be able to zoom out and look at all the hooks in one place more easily than is currently possible. But we don't want this info to be duplicated (and risk getting out of sync) so I think it'd be nice to create a script that generates one summary page for all the hooks. Maybe they'd be listed alphabetically, or maybe by category. I think it'd also be nice to include a short description of each hook in this summary page. This could be extracted out of the "description" content in each hook page. If certain hooks have long descriptions, then we could move that text down into later sections of the hooks page to keep the summary page nice and clean.

**Comment by mickadoo** [comment]
This would definitely be nice to see. Do you think this should be implemented in the [docs generator](https://lab.civicrm.org/documentation/docs-publisher) or as part of mkdocs?

**Comment by seanmadsen** [comment]
@mickadoo I was imagining the implementation would be like this: 

* a custom script lives within *this* repo
* language for script is decided by the person who implements
* documentation exists for how to run the script
* when the script runs, it reads hooks markdown files and writes (auto-generates) one "hooks summary" markdown file
* docs project managers like me become responsible for remembering that this script needs to be run after hooks files are updated
* anyone can run the script, and ideally any person who makes relevant edits to hooks files knows (perhaps by reminder) that they must run the script
* the person who runs the script then commits (into this repo) the changes which the script makes

Downsides to this approach: 

* possibility of making a change to hooks docs (e.g. adding a new hook), and forgetting to run the script, which leaves the summary page out of sync 

I can think of other approaches too (e.g. script is run automatically when publishing, as you suggest), and I'm open to other approaches. I imagine it might be tough to find an approach which has zero downsides.

**Comment by mickadoo** [comment]
I thought I'd check with the mkdocs team if there's anything they could suggest - no answers on the [Google Groups post](https://groups.google.com/forum/#!topic/mkdocs/VGqJNQmV9n4) yet

**Comment by mickadoo** [comment]
Got a [reply](https://groups.google.com/forum/#!topic/mkdocs/VGqJNQmV9n4) from one of the developers, basically saying that this might be possible in the future, but for now it's better to create a wrapper script for building that generates a hooks overview markdown file before running mkdocs.

**Comment by xurizaemon** [comment]
Just putting this here, I know it's on Sean's radar already: civicrm/civicrm-user-guide#148

**Comment by mickadoo** [comment]
@xurizaemon looks nice, I guess we could do something similar with hooks, like in your showallthehooks extension. 

Correct me if I'm wrong, but won't this [JS file](https://gist.github.com/xurizaemon/e66ed3d0127907284728ef79be57363c) require a working CiviCRM instance?

**Comment by mickadoo** [comment]
I've created a #205 for this. I think it could still be improved because right now it's still a script that must be run manually. We could add this to a `build.sh` file which I originally added, but then I deleted it because it's another complication in the build process, and I'd like to keep it as simple as possible.

I'm not sure the best approach to deal with this. Here are some options:

1. Leave it as it is and require someone to manually run the `bin/hook-make-list.sh` script when hooks change
1. Require a `build.sh` file that does everything for each guide repository (e.g. create the same script in the user guide too. The docs publisher would then look for this script and call it instead of vanilla mkdocs when publishing
1. For each guide, like this repo, create some sort of info file at the top level, like Guide.php which would implement `preBuild` and `postBuild` methods. We could use the event dispatcher to call these methods.
1. Define a particular directory where "pre" and "post" mkdocs scripts can reside inside a guide repo, e.g. `<repo>/bin/pre_build.sh` and execute them for all guides when publishing

I think option 3 is fairly nice in that it's keeping with the Symfony way of doing things (think Guide = Bundle). 

However I think 3 and 4 fall down because when I'm developing locally using only the single guide I won't see the changes in the hooks overview because it's handled by the publisher. It creates a difference between what you see when you work locally and what you see in production. 

This would also mean that changes in the overview file would never be checked in.. and that means the first time you clone the dev guide repo the mkdocs.yml will point to a file that doesn't exist yet.

I think 1 is simplest, but manual, so easy to forget.

I think 2 is nice because it's simple and easy to standardize.. we just would have to make sure to document it well.

**Comment by seanmadsen** [comment]
This is great @mickadoo! I like the options you've laid out above and agree that it's worth putting some thought into which one we want to use.

For now, I prefer **option 1** because: it's simple, it keeps content committed in git (so available locally and avoids problems with broken links), and it will be easiest to switch *away* from in the future if/when we decide to pursue a more sophisticated approach as our needs/ideas continue to evolve. 

Here's another idea to toss out there (but not one that I'm planning to pursue right away)...

I've been contemplating the idea of adding some automated tests to the guides, individually, which check for errors like broken links, spelling, and such. I've seen this with some other docs projects and it's cool. Then we could set up a CI pipeline which runs the tests on PRs and complains if they fail. As part of that pipeline we could incorporate an automated test which runs any auto-docs scripts and then checks git to ensure that nothing has changed. 

Again that's not something I'd like to do right away, but what I like about option 1 above is that it's simple for now and keeps our options open.

**Comment by mickadoo** [comment]
Sure, if you like option 1 then I'm happy to.. do nothing :-)

It's a good point about keeping it minimal, since this problem might be fixed by changes with mkdocs in the future.

Interesting idea about tests. I thought it might be part of the docs-publisher to check that published guides are viewable, but having specific tests to check for broken links does seem more like the realm of the guides repos themselves.

That sounds like an interesting project, spellchecking, link checking etc. For link checking I guess it would be simple enough to check external links. For internal I guess we could just check if the md file exists. Spelling shouldn't be too hard either. It would also be great to have CI set up, I've done it with Travis before and it was surprisingly painless. Is there an issue for this?

**Comment by seanmadsen** [comment]
This is done now. Closing
