### ISSUE TITLE
Can rewrite rules in the wiki get automatically registered on merge of a PR

### ISSUE THREAD

**Issue by michaelmcandrew** [civicrm/civicrm-dev-docs#23]
My understanding is that apache will need to be restarted for new rewrites to take effect, and I am wondering if you have consideded automating this? Via a github webhook or similar.

Feel free to correct me if my understanding is not correct.

**Comment by totten** [comment]
@michaelmcandrew That sounds more like nginx to me. ;) In Apache, I think it depends:

 * If you change anything in a `<VirtualHost>` (including a `RewriteRule`), then you **do** need to restart Apache.
 * If you change anything in a `.htaccess` (including a `RewriteRule`), then you do **not** need to restart Apache.
 * If you change anything in a `*.txt` file used by `RewriteMap`, then you do **not** need to restart Apache. This is technique used for INFRA-230.

From [the Apache docs for using RewriteMap with `*.txt` files](https://httpd.apache.org/docs/current/rewrite/rewritemap.html):

> The looked-up keys are cached by httpd until the mtime (modified time) of the mapfile changes, or the httpd server is restarted. This ensures better performance on maps that are called by many requests. 

However, there is currently a delay of up to 10 min before `java-prod` fetches the latest content from `git`. If that's a problem, then either:
 * Edit the crontab for user `confluence` on `java-prod`.
 * Setup some kind of github webhook mechanism.

**Comment by seanmadsen** [comment]
I think that the resolution of [INFRA-230](https://issues.civicrm.org/jira/browse/INFRA-230) means we can close this issue here. Am I right @totten and @michaelmcandrew? If not, what else needs to be done? And if the work to be done is server-related, then can we create a new issue within INFRA to track that work, and close this issue?

I'm trying to clean up the Dev Guide issue queue and keep its scope constrained (as much as possible) to issues that can be fixed by changing code within the Dev Guide. So if there's work to be done within the Dev Guide to close this issue, then I think we can add some clarification here and keep this issue open.

**Comment by michaelmcandrew** [comment]
i think so, yes - it was originally opened based on a misunderstanding from me...
