### ISSUE TITLE
Rationalise CiviCRM.org page and dev-guide

### ISSUE THREAD

**Issue by ErichBSchulz** [civicrm/civicrm-dev-docs#40]
I just looked at this page:

https://civicrm.org/developer-resources

I am wondering if we shouldnt incorporate any missing content (although it maybe there alread) and simply make this page into a redirect to 

https://docs.civicrm.org/dev/en/master/ ?

**Comment by michaelmcandrew** [comment]
This makes me wonder about how we are linking to the documentation from our home page in general.

Talking home page menus is opening a can of worms with many masters, so something to do gingerly.

We can definitely improve the current situation. I just can't work out how :p

**Comment by michaelmcandrew** [comment]
(not impossible, of course, and fresh eyes and energy might help)

**Comment by seanmadsen** [comment]
I'm closing this issue because: 

1. I've proposed [changes](https://github.com/civicrm/civicrm-dev-docs/pull/51) to the Dev Guide to address the content reconciliation between these two sources 
1. The remaining task is to make changes to civicrm.org, which I believe is outside the scope of this issue queue. I've requested this change in a [new issue in Jira](https://issues.civicrm.org/jira/browse/INFRA-235)
