### ISSUE TITLE
Entity name is written in pascal case insted of camel case 

### ISSUE THREAD

**Issue by asha15** [civicrm/civicrm-dev-docs#776]
Add a new entity section in the 'https://docs.civicrm.org/dev/en/latest/extensions/civix/' documentation, provide an example to generate a new entity 

> $ civix generate:entity MyEntity

The entity name is in the pascal case and it should be change for camel case

> $ civix generate:entity myEntity

I would like to submit a PR if the issue is approved

**Comment by MikeyMJCO** [comment]
There isn't - as far as I know - concrete rules on this. From what I can see a number (maybe all) core entities use pascal case. I'd like @totten or @seamuslee001 to weigh in on this first.

**Comment by totten** [comment]
Notwithstanding a caveat (below)... API entity names are canonically `UpperCamelCase` (`MyEntity`).

In APIv4, I'm pretty sure this is mandatory:

* Entity names must be `UpperCamelCase`.
* Action names must be `lowerCamelCase`.

The caveat is that APIv2/APIv3 are more... fun.

* Suppose you make a file like `api/v3/FooBar.php`. This is conventional/correct.
* It's equally valid to submit API calls in `UpperCamelCase` (`civicrm_api3('FooBar', ...)`) or `lower_snake_case` (`civicrm_api3('foo_bar', ...)`). The entity name is [filtered/normalized](https://lab.civicrm.org/dev/core/blob/5.23/Civi/API/Request.php#L55).
* The APIv3 normalization function is exceedingly forgiving. Observe that all of these are normalized to `FooBar`:
    <img width="1063" alt="Screen Shot 2020-03-03 at 2 27 16 AM" src="https://user-images.githubusercontent.com/1336047/75766793-8e758c80-5cf6-11ea-88e2-1375a7908e26.png">
* *Entity names* and *action names* have completely different rules. Because why not?
* The safest play for action names is to use `alllowercaseoneword`. But if you're coding by hand, it should be possible to do `lower_snake` (like in the `Job.process_mailing` API).

With all that said... I wouldn't be surprised if there was some buggy edge-case wherein one could work-around by changing the capitalization.

**Comment by MikeyMJCO** [comment]
Closing as per @totten's comment.
