### ISSUE TITLE
Document apiv4 save() action

### ISSUE THREAD

**Issue by eileenmcnaughton** [civicrm/civicrm-dev-docs#837]
@colemanw I can never remember how this one works...

**Comment by colemanw** [comment]
It's exactly the same as v3 *create* except the values are one layer down and multivalued. So instead of 

**APIv3**
```
$params['first_name'] = 'Bob';
```
```
$params['values'][0]['first_name'] = 'Bob';
```

**Comment by eileenmcnaughton** [comment]
@colemanw I'm not sure the explorer docs do close this out as I think the dev-docs need to cover it too

**Comment by colemanw** [comment]
@eileenmcnaughton you know I've never been a fan of keeping the same info in multiple places. I've been leaning more heavily toward source-code docblocks because they serve the dual-purpose of also getting displayed in the API explorer. I wonder if there is also some way to display them in our online docs? Any thoughts on that @MikeyMJCO ?

**Comment by eileenmcnaughton** [comment]
@colemanw fair point - it's just the docs currently do have other actions - but perhaps a better solution is out there

**Comment by colemanw** [comment]
@eileen https://docs.civicrm.org/dev/en/latest/api/v4/actions does have the Save action, but that page is not very descriptive for any of the actions. Frankly I think that page should go, and just refer people to the API Explorer, since static docs really don't work well for API actions which can vary from one entity to the next.

**Comment by colemanw** [comment]
@eileen https://docs.civicrm.org/dev/en/latest/api/v4/actions does have the Save action, but that page is not very descriptive for any of the actions. Frankly I think that page should go, and just refer people to the API Explorer, since static docs really don't work well for API actions which can vary from one entity to the next.

**Comment by eileenmcnaughton** [comment]
@colemanw I agree that page should go - but https://docs.civicrm.org/dev/en/latest/api/v4/usage/ is the one I was aware of

**Comment by colemanw** [comment]
@eileenmcnaughton  https://docs.civicrm.org/dev/en/latest/api/v4/actions does have the Save action, but that page is not very descriptive for any of the actions. Frankly I think that page should go, and just refer people to the API Explorer, since static docs really don't work well for API actions which can vary from one entity to the next.

**Comment by colemanw** [comment]
I've added a more complete list of actions including save at #840
